### ISSUE TITLE
ui: example request link doesn't work

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-oauth2server#122]
![screen shot 2017-07-28 at 13 19 19](https://user-images.githubusercontent.com/1698163/28715289-7f22cfe0-7397-11e7-8661-f954cdeb6553.png)

**Comment by dinosk** [comment]
Currently the error I get is because of trying to use https:
```
127.0.0.1 - - [01/Aug/2017 14:23:23] "GET /account/settings/applications/clients/UnYTZAMu6MibYdJPMkl8fGhuj8KKs9S2TJfPRX94/ HTTP/1.1" 200 -
127.0.0.1 - - [01/Aug/2017 14:23:25] code 400, message Bad request syntax ('\x16\x03\x01\x00Ö\x01\x00\x00Ò\x03\x03Y\x80r½|ÑY\x06Ù\x89IìLåì{þ\x128;ª\x90ë¨ÚÂ\x10\x88\x81,\x06S\x00\x00&\x00ÿÀ,À+À$À#À')
```

There are some ways to let Flask serve https, like using `pyopenssl` and adding `app.run(ssl_context='adhoc')` but I think that this is only an issue when running the server for development. Should I go ahead using pyopenssl or is there another way to go?
